# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Note: Machine's ip is 192.168.33.10
# username : vagrant
# password : vagrant
#
# accumulo instance : dev
# accumulo username : root
# accumulo password : root

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "rya-example-box"
    vb.memory = "4096"
	vb.cpus = 4
  end

  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.hostname = "rya-example-box"

  config.vm.provision "shell", inline: <<-SHELL
    echo "Updating host file with permanent ip"
	sudo sed -i 's/127.0.1.1/192.168.33.10/' /etc/hosts
    cat >> /etc/hosts <<EOF
192.168.33.10 zoo1 zoo2 zoo3
EOF

    sudo apt-get update
    
    echo "Installing Sun Java..."
    sudo add-apt-repository ppa:webupd8team/java
    sudo apt-get update
    echo debconf shared/accepted-oracle-license-v1-1 select true | \
      sudo /usr/bin/debconf-set-selections
    echo debconf shared/accepted-oracle-license-v1-1 seen true | \
      sudo /usr/bin/debconf-set-selections
    sudo apt-get install -y oracle-java8-installer
    sudo ln -s /usr/lib/jvm/java-8-oracle/ /usr/lib/jvm/default-java
    
    echo "Installing Tomcat..."
    sudo apt-get install -y tomcat7
    
    echo "Installing Unzip..."
    apt-get install unzip

    echo "Setting up environment..."
    export JAVA_HOME=/usr/lib/jvm/java-8-oracle
    export HADOOP_HOME=/home/vagrant/hadoop-1.2.1
    export ZOOKEEPER_HOME=/home/vagrant/zookeeper-3.4.5-cdh4.5.0
    export ACCUMULO_HOME=/home/vagrant/accumulo-1.6.4
    export PATH=$PATH:$JAVA_HOME/bin:$ZOOKEEPER_HOME/bin:$ACCUMULO_HOME/bin

    export HADOOP_PREFIX="$HADOOP_HOME"
    export HADOOP_CONF_DIR="$HADOOP_PREFIX/conf"
    export ACCUMULO_LOG_DIR=$ACCUMULO_HOME/logs
    export ACCUMULO_TSERVER_OPTS="-Xmx384m -Xms384m "
    export ACCUMULO_MASTER_OPTS="-Xmx128m -Xms128m"
    export ACCUMULO_MONITOR_OPTS="-Xmx64m -Xms64m"
    export ACCUMULO_GC_OPTS="-Xmx64m -Xms64m"
    export ACCUMULO_GENERAL_OPTS="-XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -Djava.net.preferIPv4Stack=true"
    export ACCUMULO_OTHER_OPTS="-Xmx128m -Xms64m"
    export ACCUMULO_KILL_CMD='kill -9 %p'

    cat >> /home/vagrant/.bashrc <<EOF
        export JAVA_HOME=/usr/lib/jvm/java-8-oracle
        export HADOOP_HOME=/home/vagrant/hadoop-1.2.1
        export ZOOKEEPER_HOME=/home/vagrant/zookeeper-3.4.5-cdh4.5.0
        export ACCUMULO_HOME=/home/vagrant/accumulo-1.6.4
        export PATH=$PATH:$JAVA_HOME/bin:$ZOOKEEPER_HOME/bin:$ACCUMULO_HOME/bin

        export HADOOP_PREFIX="$HADOOP_HOME"
        export HADOOP_CONF_DIR="$HADOOP_PREFIX/conf"
        export ACCUMULO_LOG_DIR=$ACCUMULO_HOME/logs
        export ACCUMULO_TSERVER_OPTS="-Xmx384m -Xms384m "
        export ACCUMULO_MASTER_OPTS="-Xmx128m -Xms128m"
        export ACCUMULO_MONITOR_OPTS="-Xmx64m -Xms64m"
        export ACCUMULO_GC_OPTS="-Xmx64m -Xms64m"
        export ACCUMULO_GENERAL_OPTS="-XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -Djava.net.preferIPv4Stack=true"
        export ACCUMULO_OTHER_OPTS="-Xmx128m -Xms64m"
        export ACCUMULO_KILL_CMD='kill -9 %p'
EOF

    
    echo "Acquiring and Extracting ..."
    
    echo "- Hadoop"
    curl -SL http://apache.mirrors.tds.net/hadoop/common/hadoop-1.2.1/hadoop-1.2.1.tar.gz \
      | tar -zxC /home/vagrant

    echo "- Zookeeper"
    curl -SL http://archive-primary.cloudera.com/cdh4/cdh/4/zookeeper-3.4.5-cdh4.5.0.tar.gz \
      | tar -zxC /home/vagrant
    
    echo "- Accumulo"
    curl -SL http://apache.mirrors.pair.com/accumulo/1.6.4/accumulo-1.6.4-bin.tar.gz \
      | tar -zxC /home/vagrant
    
    echo "Configuring Zookeeper..."
    sudo mkdir /var/zookeeper
    sudo chown vagrant:vagrant /var/zookeeper

    echo "Running Zookeeper..."
    cp zookeeper-3.4.5-cdh4.5.0/conf/zoo_sample.cfg zookeeper-3.4.5-cdh4.5.0/conf/zoo.cfg
    sudo zookeeper-3.4.5-cdh4.5.0/bin/zkServer.sh start
    
    echo "Configuring Accumulo..."
    cp accumulo-1.6.4/conf/examples/1GB/standalone/* accumulo-1.6.4/conf/
    rm accumulo-1.6.4/conf/accumulo-site.xml
    cat >> accumulo-1.6.4/conf/accumulo-site.xml <<EOF
        <configuration>
            <property><name>instance.dfs.uri</name><value>file:///</value></property>
            <property><name>instance.dfs.dir</name><value>/data/accumulo</value></property>
            <property><name>instance.zookeeper.host</name><value>localhost:2181</value></property>
            <property><name>instance.secret</name><value>DONTTELL</value></property>
            <property><name>tserver.port.search</name><value>true</value></property>
            <property><name>logger.dir.walog</name><value>/data/accumulo/walogs</value></property>
            <property><name>tserver.cache.data.size</name><value>15M</value></property>
            <property><name>tserver.cache.index.size</name><value>15M</value></property>
            <property><name>tserver.memory.maps.max</name><value>256M</value></property>
            <property><name>tserver.walog.max.size</name><value>256M</value></property>
            <property><name>tserver.memory.maps.native.enabled</name><value>false</value></property>
            <property><name>trace.token.property.password</name><value>root</value></property>
            <property><name>gc.cycle.delay</name><value>4s</value></property>
            <property><name>gc.cycle.start</name><value>0s</value></property>
            <property><name>tserver.compaction.major.delay</name><value>3</value></property>
            <property><name>general.classpaths</name><value>
            /data/accumulo/lib/[^.].*.jar,
            /home/vagrant/hadoop-1.2.1/share/hadoop/common/.*.jar,
            /home/vagrant/hadoop-1.2.1/share/hadoop/common/lib/.*.jar,
            /home/vagrant/hadoop-1.2.1/share/hadoop/hdfs/.*.jar,
            /home/vagrant/hadoop-1.2.1/share/hadoop/mapreduce/.*.jar,
            /home/vagrant/hadoop-1.2.1/share/hadoop/yarn/.*.jar,
            /home/vagrant/accumulo-1.6.4/server/target/classes/,
            /home/vagrant/accumulo-1.6.4/lib/accumulo-server.jar,
            /home/vagrant/accumulo-1.6.4/core/target/classes/,
            /home/vagrant/accumulo-1.6.4/lib/accumulo-core.jar,
            /home/vagrant/accumulo-1.6.4/start/target/classes/,
            /home/vagrant/accumulo-1.6.4/lib/accumulo-start.jar,
            /home/vagrant/accumulo-1.6.4/fate/target/classes/,
            /home/vagrant/accumulo-1.6.4/lib/accumulo-fate.jar,
            /home/vagrant/accumulo-1.6.4/proxy/target/classes/,
            /home/vagrant/accumulo-1.6.4/lib/accumulo-proxy.jar,
            /home/vagrant/accumulo-1.6.4/lib/[^.].*.jar,
            /home/vagrant/zookeeper-3.4.5-cdh4.5.0/zookeeper[^.].*.jar,
            $HADOOP_CONF_DIR,
            /home/vagrant/hadoop-1.2.1/[^.].*.jar,
            /home/vagrant/hadoop-1.2.1/lib/[^.].*.jar,
            </value></property>
            <property><name>general.dynamic.classpaths</name><value>/data/accumulo/lib/ext/[^.].*.jar</value></property>
            <property><name>trace.port.client</name><value>0</value></property>
            <property><name>monitor.port.client</name><value>0</value></property>
            <property><name>master.port.client</name><value>0</value></property>
            <property><name>tserver.port.client</name><value>0</value></property>
            <property><name>gc.port.client</name><value>0</value></property>
        </configuration>
EOF
    cat > accumulo-1.6.4/conf/masters <<EOF
rya-example-box
EOF

	cat > accumulo-1.6.4/conf/slaves <<EOF
rya-example-box
EOF
    sudo mkdir /data
    sudo chown vagrant:vagrant /data
    mkdir /data/accumulo
    mkdir /data/accumulo/lib
    mkdir /data/accumulo/lib/ext

    echo "Starting Accumulo..."
    accumulo-1.6.4/bin/accumulo init --instance-name dev --password root
    accumulo-1.6.4/bin/start-all.sh

    echo 'Done!'

	echo "Installing Sesame Server"
	# creating log dir sesame-http-server-2.7.6
	sudo mkdir -p /usr/share/tomcat7/.aduna 
	sudo chown -R tomcat7:tomcat7 /usr/share/tomcat7  
    sudo ln -s /usr/share/tomcat7/.aduna/openrdf-sesame/logs /var/log/tomcat7/openrdf-sesame
	
	sudo curl -O http://repo1.maven.org/maven2/org/openrdf/sesame/sesame-http-server/2.7.6/sesame-http-server-2.7.6.war
	sudo mv sesame-http-server-2.7.6.war /var/lib/tomcat7/webapps/openrdf-sesame.war
	echo "Sesame http server deployed at http://rya-example-box:8080/openrdf-sesame"
	
	echo "Installing Sesame Workbench"
	sudo curl -O http://repo1.maven.org/maven2/org/openrdf/sesame/sesame-http-workbench/2.7.6/sesame-http-workbench-2.7.6.war
	sudo mv sesame-http-workbench-2.7.6.war /var/lib/tomcat7/webapps/openrdf-workbench.war
	echo "Sesame workbench deployed at http://rya-example-box:8080/openrdf-workbench"

	echo "Downloading Rya"
	# Right now it's on dropbox, but eventually it'll be on maven...

	sudo curl -L https://www.dropbox.com/s/7e74yiuq4jmu0od/rya.indexing.example-3.2.10-SNAPSHOT-distribution.zip?dl=0 -o rya.indexing.example-3.2.10-SNAPSHOT-distribution.zip
	sudo mkdir rya.indexing.example-3.2.10-SNAPSHOT-distribution
	sudo unzip rya.indexing.example-3.2.10-SNAPSHOT-distribution.zip -d rya.indexing.example-3.2.10-SNAPSHOT-distribution
	
	# soft linking the files doesn't seem to work in tomcat, so we copy them instead :(
	sudo cp rya.indexing.example-3.2.10-SNAPSHOT-distribution/dist/lib/* /var/lib/tomcat7/webapps/openrdf-workbench/WEB-INF/lib/
	sudo cp rya.indexing.example-3.2.10-SNAPSHOT-distribution/dist/lib/* /var/lib/tomcat7/webapps/openrdf-sesame/WEB-INF/lib/

	# These are older libs that breaks tomcat 7
	sudo rm /var/lib/tomcat7/webapps/openrdf-workbench/WEB-INF/lib/servlet-api-2.5.jar
	sudo rm /var/lib/tomcat7/webapps/openrdf-workbench/WEB-INF/lib/jsp-api-2.1.jar
	sudo rm /var/lib/tomcat7/webapps/openrdf-sesame/WEB-INF/lib/servlet-api-2.5.jar
	sudo rm /var/lib/tomcat7/webapps/openrdf-sesame/WEB-INF/lib/jsp-api-2.1.jar
	
	sudo chown -R tomcat7:tomcat7 /var/lib/tomcat7/webapps/openrdf-workbench/WEB-INF/lib/
	sudo chown -R tomcat7:tomcat7 /var/lib/tomcat7/webapps/openrdf-sesame/WEB-INF/lib/

	# Download and install new templates for OpenRdf WorkBench
	sudo curl -L -O https://www.dropbox.com/s/dgw63m66nubyy4z/rya.vagrant.example-3.2.10-SNAPSHOT.jar
	sudo mkdir rya.vagrant.example-3.2.10-SNAPSHOT
	sudo unzip rya.vagrant.example-3.2.10-SNAPSHOT.jar -d rya.vagrant.example-3.2.10-SNAPSHOT
	sudo cp rya.vagrant.example-3.2.10-SNAPSHOT/*.xsl /var/lib/tomcat7/webapps/openrdf-workbench/transformations/
	
	echo "Deploying Rya Web"
	sudo curl -L https://www.dropbox.com/s/332wr4b2f34dp6e/web.rya-3.2.10-SNAPSHOT.war?dl=0 -o web.rya.war
	sudo cp web.rya.war /var/lib/tomcat7/webapps/web.rya.war
	# Wait for the war to deploy
	sudo sleep 10
	# These are older libs that breaks tomcat 7
	sudo rm /var/lib/tomcat7/webapps/web.rya/WEB-INF/lib/servlet-api-2.5*.jar
	sudo rm /var/lib/tomcat7/webapps/web.rya/WEB-INF/lib/jsp-api-2.1.jar

	echo "Modify Rya Web Config"
	cat > /var/lib/tomcat7/webapps/web.rya/WEB-INF/classes/environment.properties <<EOF
instance.name=dev
instance.zk=localhost:2181
instance.username=root
instance.password=root
rya.tableprefix=rya_
rya.displayqueryplan=true
EOF

	echo "Rya web deployed at http://rya-example-box:8080/web.rya/sparqlQuery.jsp"
	
	# restart tomcat
	sudo service tomcat7 restart
	


	
	
  SHELL

end
